/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MinhaViagemRouteImport } from './routes/minha-viagem'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JornadaMadrinhaRouteImport } from './routes/jornada-madrinha'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CarteiraRouteImport } from './routes/carteira'
import { Route as CandidaturaRouteImport } from './routes/candidatura'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as AreamadrinhaRouteImport } from './routes/areamadrinha'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MadrinhaIdRouteImport } from './routes/madrinha.$id'

const MinhaViagemRoute = MinhaViagemRouteImport.update({
  id: '/minha-viagem',
  path: '/minha-viagem',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JornadaMadrinhaRoute = JornadaMadrinhaRouteImport.update({
  id: '/jornada-madrinha',
  path: '/jornada-madrinha',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteiraRoute = CarteiraRouteImport.update({
  id: '/carteira',
  path: '/carteira',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidaturaRoute = CandidaturaRouteImport.update({
  id: '/candidatura',
  path: '/candidatura',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const AreamadrinhaRoute = AreamadrinhaRouteImport.update({
  id: '/areamadrinha',
  path: '/areamadrinha',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MadrinhaIdRoute = MadrinhaIdRouteImport.update({
  id: '/madrinha/$id',
  path: '/madrinha/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/areamadrinha': typeof AreamadrinhaRoute
  '/busca': typeof BuscaRoute
  '/cadastro': typeof CadastroRoute
  '/candidatura': typeof CandidaturaRoute
  '/carteira': typeof CarteiraRoute
  '/dashboard': typeof DashboardRoute
  '/jornada-madrinha': typeof JornadaMadrinhaRoute
  '/login': typeof LoginRoute
  '/minha-viagem': typeof MinhaViagemRoute
  '/madrinha/$id': typeof MadrinhaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/areamadrinha': typeof AreamadrinhaRoute
  '/busca': typeof BuscaRoute
  '/cadastro': typeof CadastroRoute
  '/candidatura': typeof CandidaturaRoute
  '/carteira': typeof CarteiraRoute
  '/dashboard': typeof DashboardRoute
  '/jornada-madrinha': typeof JornadaMadrinhaRoute
  '/login': typeof LoginRoute
  '/minha-viagem': typeof MinhaViagemRoute
  '/madrinha/$id': typeof MadrinhaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/areamadrinha': typeof AreamadrinhaRoute
  '/busca': typeof BuscaRoute
  '/cadastro': typeof CadastroRoute
  '/candidatura': typeof CandidaturaRoute
  '/carteira': typeof CarteiraRoute
  '/dashboard': typeof DashboardRoute
  '/jornada-madrinha': typeof JornadaMadrinhaRoute
  '/login': typeof LoginRoute
  '/minha-viagem': typeof MinhaViagemRoute
  '/madrinha/$id': typeof MadrinhaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/areamadrinha'
    | '/busca'
    | '/cadastro'
    | '/candidatura'
    | '/carteira'
    | '/dashboard'
    | '/jornada-madrinha'
    | '/login'
    | '/minha-viagem'
    | '/madrinha/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/areamadrinha'
    | '/busca'
    | '/cadastro'
    | '/candidatura'
    | '/carteira'
    | '/dashboard'
    | '/jornada-madrinha'
    | '/login'
    | '/minha-viagem'
    | '/madrinha/$id'
  id:
    | '__root__'
    | '/'
    | '/areamadrinha'
    | '/busca'
    | '/cadastro'
    | '/candidatura'
    | '/carteira'
    | '/dashboard'
    | '/jornada-madrinha'
    | '/login'
    | '/minha-viagem'
    | '/madrinha/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AreamadrinhaRoute: typeof AreamadrinhaRoute
  BuscaRoute: typeof BuscaRoute
  CadastroRoute: typeof CadastroRoute
  CandidaturaRoute: typeof CandidaturaRoute
  CarteiraRoute: typeof CarteiraRoute
  DashboardRoute: typeof DashboardRoute
  JornadaMadrinhaRoute: typeof JornadaMadrinhaRoute
  LoginRoute: typeof LoginRoute
  MinhaViagemRoute: typeof MinhaViagemRoute
  MadrinhaIdRoute: typeof MadrinhaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/minha-viagem': {
      id: '/minha-viagem'
      path: '/minha-viagem'
      fullPath: '/minha-viagem'
      preLoaderRoute: typeof MinhaViagemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jornada-madrinha': {
      id: '/jornada-madrinha'
      path: '/jornada-madrinha'
      fullPath: '/jornada-madrinha'
      preLoaderRoute: typeof JornadaMadrinhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carteira': {
      id: '/carteira'
      path: '/carteira'
      fullPath: '/carteira'
      preLoaderRoute: typeof CarteiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidatura': {
      id: '/candidatura'
      path: '/candidatura'
      fullPath: '/candidatura'
      preLoaderRoute: typeof CandidaturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areamadrinha': {
      id: '/areamadrinha'
      path: '/areamadrinha'
      fullPath: '/areamadrinha'
      preLoaderRoute: typeof AreamadrinhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/madrinha/$id': {
      id: '/madrinha/$id'
      path: '/madrinha/$id'
      fullPath: '/madrinha/$id'
      preLoaderRoute: typeof MadrinhaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AreamadrinhaRoute: AreamadrinhaRoute,
  BuscaRoute: BuscaRoute,
  CadastroRoute: CadastroRoute,
  CandidaturaRoute: CandidaturaRoute,
  CarteiraRoute: CarteiraRoute,
  DashboardRoute: DashboardRoute,
  JornadaMadrinhaRoute: JornadaMadrinhaRoute,
  LoginRoute: LoginRoute,
  MinhaViagemRoute: MinhaViagemRoute,
  MadrinhaIdRoute: MadrinhaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
